In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
df = pd.read_csv("/content/test.csv")
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
0,0x2318,COIMBRES13DEL01,NaN,NaN,11.003669,76.976494,11.043669,77.016494,30-03-2022,NaN,15:05:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian
1,0x3474,BANGRES15DEL01,28,4.6,12.975377,77.696664,13.085377,77.806664,29-03-2022,20:30:00,20:35:00,conditions Windy,Jam,0,Snack,motorcycle,1,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,4.5,26.911378,75.789034,27.001378,75.879034,10-03-2022,19:35:00,19:45:00,conditions Stormy,Jam,0,Drinks,motorcycle,1,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,4.8,26.766536,75.837333,26.856536,75.927333,02-04-2022,17:15:00,17:20:00,conditions Fog,Medium,1,Meal,scooter,1,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,4.6,12.986047,80.218114,13.096047,80.328114,27-03-2022,18:25:00,18:40:00,conditions Sunny,Medium,2,Drinks,scooter,1,No,Metropolitian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11394,0x6909,JAPRES01DEL01,35,4.6,26.905190,75.810753,27.015190,75.920753,27-03-2022,21:35:00,21:45:00,conditions Sunny,Jam,1,Snack,scooter,1,No,Metropolitian
11395,0x443b,JAPRES11DEL01,33,4.9,26.902940,75.793007,26.912940,75.803007,11-03-2022,11:40:00,11:45:00,conditions Sandstorms,High,1,Drinks,scooter,1,No,Metropolitian
11396,0x1ea5,SURRES11DEL03,NaN,NaN,21.157735,72.768778,21.217735,72.828778,11-03-2022,NaN,21:05:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian
11397,0x22d4,VADRES03DEL02,27,4.7,22.320000,73.170000,22.450000,73.300000,06-03-2022,18:35:00,18:40:00,conditions Sandstorms,Medium,0,Meal,motorcycle,0,No,Metropolitian
11398,0xb7be,CHENRES07DEL02,39,5,13.081878,80.248519,13.131878,80.298519,24-03-2022,22:20:00,22:25:00,conditions Windy,Low,2,Drinks,motorcycle,1,No,Urban

In [3]:
df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11399 entries, 0 to 11398
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           11399 non-null  object
 1   Delivery_person_ID           11399 non-null  object
 2   Delivery_person_Age          11399 non-null  object
 3   Delivery_person_Ratings      11399 non-null  object
 4   Restaurant_latitude          11399 non-null  float64
 5   Restaurant_longitude         11399 non-null  float64
 6   Delivery_location_latitude   11399 non-null  float64
 7   Delivery_location_longitude  11399 non-null  float64
 8   Order_Date                   11399 non-null  object
 9   Time_Orderd                  11399 non-null  object
 10  Time_Order_picked            11399 non-null  object
 11  Weatherconditions            11399 non-null  object
 12  Road_traffic_density         11399 non-null  object
 13  Vehicle_condition            11399 non-null  int64
 14  Type_of_order                11399 non-null  object
 15  Type_of_vehicle              11399 non-null  object
 16  multiple_deliveries          11399 non-null  object
 17  Festival                     11399 non-null  object
 18  City                         11399 non-null  object
dtypes: float64(4), int64(1), object(14)
memory usage: 1.7+ MB

In [5]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
0,0x2318,COIMBRES13DEL01,NaN,NaN,11.003669,76.976494,11.043669,77.016494,30-03-2022,NaN,15:05:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian
1,0x3474,BANGRES15DEL01,28,4.6,12.975377,77.696664,13.085377,77.806664,29-03-2022,20:30:00,20:35:00,conditions Windy,Jam,0,Snack,motorcycle,1,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,4.5,26.911378,75.789034,27.001378,75.879034,10-03-2022,19:35:00,19:45:00,conditions Stormy,Jam,0,Drinks,motorcycle,1,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,4.8,26.766536,75.837333,26.856536,75.927333,02-04-2022,17:15:00,17:20:00,conditions Fog,Medium,1,Meal,scooter,1,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,4.6,12.986047,80.218114,13.096047,80.328114,27-03-2022,18:25:00,18:40:00,conditions Sunny,Medium,2,Drinks,scooter,1,No,Metropolitian

In [6]:
df.replace(
    ["NaN ", "N/A", "null", "-"],
    np.nan,
    inplace=True
)

In [7]:
df

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
0,0x2318,COIMBRES13DEL01,NaN,NaN,11.003669,76.976494,11.043669,77.016494,30-03-2022,NaN,15:05:00,conditions NaN,NaN,3,Drinks,electric_scooter,1,No,Metropolitian
1,0x3474,BANGRES15DEL01,28,4.6,12.975377,77.696664,13.085377,77.806664,29-03-2022,20:30:00,20:35:00,conditions Windy,Jam,0,Snack,motorcycle,1,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,4.5,26.911378,75.789034,27.001378,75.879034,10-03-2022,19:35:00,19:45:00,conditions Stormy,Jam,0,Drinks,motorcycle,1,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,4.8,26.766536,75.837333,26.856536,75.927333,02-04-2022,17:15:00,17:20:00,conditions Fog,Medium,1,Meal,scooter,1,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,4.6,12.986047,80.218114,13.096047,80.328114,27-03-2022,18:25:00,18:40:00,conditions Sunny,Medium,2,Drinks,scooter,1,No,Metropolitian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11394,0x6909,JAPRES01DEL01,35,4.6,26.905190,75.810753,27.015190,75.920753,27-03-2022,21:35:00,21:45:00,conditions Sunny,Jam,1,Snack,scooter,1,No,Metropolitian
11395,0x443b,JAPRES11DEL01,33,4.9,26.902940,75.793007,26.912940,75.803007,11-03-2022,11:40:00,11:45:00,conditions Sandstorms,High,1,Drinks,scooter,1,No,Metropolitian
11396,0x1ea5,SURRES11DEL03,NaN,NaN,21.157735,72.768778,21.217735,72.828778,11-03-2022,NaN,21:05:00,conditions NaN,NaN,3,Drinks,scooter,1,No,Metropolitian
11397,0x22d4,VADRES03DEL02,27,4.7,22.320000,73.170000,22.450000,73.300000,06-03-2022,18:35:00,18:40:00,conditions Sandstorms,Medium,0,Meal,motorcycle,0,No,Metropolitian
11398,0xb7be,CHENRES07DEL02,39,5,13.081878,80.248519,13.131878,80.298519,24-03-2022,22:20:00,22:25:00,conditions Windy,Low,2,Drinks,motorcycle,1,No,Urban

In [8]:
df.isnull().sum()

ID                               0
Delivery_person_ID               0
Delivery_person_Age            491
Delivery_person_Ratings        507
Restaurant_latitude              0
Restaurant_longitude             0
Delivery_location_latitude       0
Delivery_location_longitude      0
Order_Date                       0
Time_Orderd                    444
Time_Order_picked                0
Weatherconditions                0
Road_traffic_density           154
Vehicle_condition                0
Type_of_order                    0
Type_of_vehicle                  0
multiple_deliveries            238
Festival                        65
City                           324
dtype: int64

In [9]:
columns = df.columns
columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City'],
      dtype='object')

In [10]:
for col in df.columns:
  if df[col].dtype == "object":
    df[col] = df[col].str.strip()

In [11]:
df.replace("NaN",np.nan,inplace = True)

In [12]:
df.isnull().sum()

ID                               0
Delivery_person_ID               0
Delivery_person_Age            491
Delivery_person_Ratings        507
Restaurant_latitude              0
Restaurant_longitude             0
Delivery_location_latitude       0
Delivery_location_longitude      0
Order_Date                       0
Time_Orderd                    444
Time_Order_picked                0
Weatherconditions                0
Road_traffic_density           154
Vehicle_condition                0
Type_of_order                    0
Type_of_vehicle                  0
multiple_deliveries            238
Festival                        65
City                           324
dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11399 entries, 0 to 11398
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           11399 non-null  object
 1   Delivery_person_ID           11399 non-null  object
 2   Delivery_person_Age          10908 non-null  object
 3   Delivery_person_Ratings      10892 non-null  object
 4   Restaurant_latitude          11399 non-null  float64
 5   Restaurant_longitude         11399 non-null  float64
 6   Delivery_location_latitude   11399 non-null  float64
 7   Delivery_location_longitude  11399 non-null  float64
 8   Order_Date                   11399 non-null  object
 9   Time_Orderd                  10955 non-null  object
 10  Time_Order_picked            11399 non-null  object
 11  Weatherconditions            11399 non-null  object
 12  Road_traffic_density         11245 non-null  object
 13  Vehicle_condition            11399 non-null  int64
 14  Type_of_order                11399 non-null  object
 15  Type_of_vehicle              11399 non-null  object
 16  multiple_deliveries          11161 non-null  object
 17  Festival                     11334 non-null  object
 18  City                         11075 non-null  object
dtypes: float64(4), int64(1), object(14)
memory usage: 1.7+ MB

In [14]:
df.dropna(inplace = True)

In [15]:
df.replace("Unknown", np.nan, inplace = True)

In [16]:
df.dropna()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
1,0x3474,BANGRES15DEL01,28,4.6,12.975377,77.696664,13.085377,77.806664,29-03-2022,20:30:00,20:35:00,conditions Windy,Jam,0,Snack,motorcycle,1,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,4.5,26.911378,75.789034,27.001378,75.879034,10-03-2022,19:35:00,19:45:00,conditions Stormy,Jam,0,Drinks,motorcycle,1,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,4.8,26.766536,75.837333,26.856536,75.927333,02-04-2022,17:15:00,17:20:00,conditions Fog,Medium,1,Meal,scooter,1,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,4.6,12.986047,80.218114,13.096047,80.328114,27-03-2022,18:25:00,18:40:00,conditions Sunny,Medium,2,Drinks,scooter,1,No,Metropolitian
5,0xc4af,GOARES04DEL01,26,4.7,15.569600,73.742294,15.579600,73.752294,15-02-2022,09:45:00,09:55:00,conditions Fog,Low,0,Drinks,motorcycle,1,No,Metropolitian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11393,0xe240,BHPRES07DEL01,31,4.7,0.000000,0.000000,0.010000,0.010000,13-02-2022,11:00:00,11:10:00,conditions Windy,Low,2,Snack,scooter,1,No,Metropolitian
11394,0x6909,JAPRES01DEL01,35,4.6,26.905190,75.810753,27.015190,75.920753,27-03-2022,21:35:00,21:45:00,conditions Sunny,Jam,1,Snack,scooter,1,No,Metropolitian
11395,0x443b,JAPRES11DEL01,33,4.9,26.902940,75.793007,26.912940,75.803007,11-03-2022,11:40:00,11:45:00,conditions Sandstorms,High,1,Drinks,scooter,1,No,Metropolitian
11397,0x22d4,VADRES03DEL02,27,4.7,22.320000,73.170000,22.450000,73.300000,06-03-2022,18:35:00,18:40:00,conditions Sandstorms,Medium,0,Meal,motorcycle,0,No,Metropolitian
11398,0xb7be,CHENRES07DEL02,39,5,13.081878,80.248519,13.131878,80.298519,24-03-2022,22:20:00,22:25:00,conditions Windy,Low,2,Drinks,motorcycle,1,No,Urban

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10291 entries, 1 to 11398
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           10291 non-null  object
 1   Delivery_person_ID           10291 non-null  object
 2   Delivery_person_Age          10291 non-null  object
 3   Delivery_person_Ratings      10291 non-null  object
 4   Restaurant_latitude          10291 non-null  float64
 5   Restaurant_longitude         10291 non-null  float64
 6   Delivery_location_latitude   10291 non-null  float64
 7   Delivery_location_longitude  10291 non-null  float64
 8   Order_Date                   10291 non-null  object
 9   Time_Orderd                  10291 non-null  object
 10  Time_Order_picked            10291 non-null  object
 11  Weatherconditions            10291 non-null  object
 12  Road_traffic_density         10291 non-null  object
 13  Vehicle_condition            10291 non-null  int64
 14  Type_of_order                10291 non-null  object
 15  Type_of_vehicle              10291 non-null  object
 16  multiple_deliveries          10291 non-null  object
 17  Festival                     10291 non-null  object
 18  City                         10291 non-null  object
dtypes: float64(4), int64(1), object(14)
memory usage: 1.8+ MB

In [18]:
df.dropna(inplace = True)

In [19]:
df

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
1,0x3474,BANGRES15DEL01,28,4.6,12.975377,77.696664,13.085377,77.806664,29-03-2022,20:30:00,20:35:00,conditions Windy,Jam,0,Snack,motorcycle,1,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,4.5,26.911378,75.789034,27.001378,75.879034,10-03-2022,19:35:00,19:45:00,conditions Stormy,Jam,0,Drinks,motorcycle,1,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,4.8,26.766536,75.837333,26.856536,75.927333,02-04-2022,17:15:00,17:20:00,conditions Fog,Medium,1,Meal,scooter,1,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,4.6,12.986047,80.218114,13.096047,80.328114,27-03-2022,18:25:00,18:40:00,conditions Sunny,Medium,2,Drinks,scooter,1,No,Metropolitian
5,0xc4af,GOARES04DEL01,26,4.7,15.569600,73.742294,15.579600,73.752294,15-02-2022,09:45:00,09:55:00,conditions Fog,Low,0,Drinks,motorcycle,1,No,Metropolitian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11393,0xe240,BHPRES07DEL01,31,4.7,0.000000,0.000000,0.010000,0.010000,13-02-2022,11:00:00,11:10:00,conditions Windy,Low,2,Snack,scooter,1,No,Metropolitian
11394,0x6909,JAPRES01DEL01,35,4.6,26.905190,75.810753,27.015190,75.920753,27-03-2022,21:35:00,21:45:00,conditions Sunny,Jam,1,Snack,scooter,1,No,Metropolitian
11395,0x443b,JAPRES11DEL01,33,4.9,26.902940,75.793007,26.912940,75.803007,11-03-2022,11:40:00,11:45:00,conditions Sandstorms,High,1,Drinks,scooter,1,No,Metropolitian
11397,0x22d4,VADRES03DEL02,27,4.7,22.320000,73.170000,22.450000,73.300000,06-03-2022,18:35:00,18:40:00,conditions Sandstorms,Medium,0,Meal,motorcycle,0,No,Metropolitian
11398,0xb7be,CHENRES07DEL02,39,5,13.081878,80.248519,13.131878,80.298519,24-03-2022,22:20:00,22:25:00,conditions Windy,Low,2,Drinks,motorcycle,1,No,Urban

In [20]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
1,0x3474,BANGRES15DEL01,28,4.6,12.975377,77.696664,13.085377,77.806664,29-03-2022,20:30:00,20:35:00,conditions Windy,Jam,0,Snack,motorcycle,1,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,4.5,26.911378,75.789034,27.001378,75.879034,10-03-2022,19:35:00,19:45:00,conditions Stormy,Jam,0,Drinks,motorcycle,1,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,4.8,26.766536,75.837333,26.856536,75.927333,02-04-2022,17:15:00,17:20:00,conditions Fog,Medium,1,Meal,scooter,1,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,4.6,12.986047,80.218114,13.096047,80.328114,27-03-2022,18:25:00,18:40:00,conditions Sunny,Medium,2,Drinks,scooter,1,No,Metropolitian
5,0xc4af,GOARES04DEL01,26,4.7,15.569600,73.742294,15.579600,73.752294,15-02-2022,09:45:00,09:55:00,conditions Fog,Low,0,Drinks,motorcycle,1,No,Metropolitian

In [21]:
df["Delivery_person_Age"] = df["Delivery_person_Age"].astype("int64")
df["Delivery_person_Ratings"] = df["Delivery_person_Age"].astype("float")

In [22]:
df["Vehicle_condition"].replace([0,1,2], ["Good","Average","Bad"], inplace = True)

/tmp/ipykernel_1003/2964716853.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Vehicle_condition"].replace([0,1,2], ["Good","Average","Bad"], inplace = True)

In [23]:
df["multiple_deliveries"].unique()

array(['1', '0', '2', '3'], dtype=object)

In [24]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
1,0x3474,BANGRES15DEL01,28,28.0,12.975377,77.696664,13.085377,77.806664,29-03-2022,20:30:00,20:35:00,conditions Windy,Jam,Good,Snack,motorcycle,1,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,23.0,26.911378,75.789034,27.001378,75.879034,10-03-2022,19:35:00,19:45:00,conditions Stormy,Jam,Good,Drinks,motorcycle,1,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,21.0,26.766536,75.837333,26.856536,75.927333,02-04-2022,17:15:00,17:20:00,conditions Fog,Medium,Average,Meal,scooter,1,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,31.0,12.986047,80.218114,13.096047,80.328114,27-03-2022,18:25:00,18:40:00,conditions Sunny,Medium,Bad,Drinks,scooter,1,No,Metropolitian
5,0xc4af,GOARES04DEL01,26,26.0,15.569600,73.742294,15.579600,73.752294,15-02-2022,09:45:00,09:55:00,conditions Fog,Low,Good,Drinks,motorcycle,1,No,Metropolitian

In [25]:
dfdummy = df.copy()

In [26]:
df["multiple_deliveries"] = df["multiple_deliveries"].astype("int64")

mapping = {0: 'Zero', 1: 'Single',2: 'Multiple', 3: "Multiple"}
df["multiple_deliveries"] = df["multiple_deliveries"].map(mapping)

In [27]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
1,0x3474,BANGRES15DEL01,28,28.0,12.975377,77.696664,13.085377,77.806664,29-03-2022,20:30:00,20:35:00,conditions Windy,Jam,Good,Snack,motorcycle,Single,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,23.0,26.911378,75.789034,27.001378,75.879034,10-03-2022,19:35:00,19:45:00,conditions Stormy,Jam,Good,Drinks,motorcycle,Single,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,21.0,26.766536,75.837333,26.856536,75.927333,02-04-2022,17:15:00,17:20:00,conditions Fog,Medium,Average,Meal,scooter,Single,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,31.0,12.986047,80.218114,13.096047,80.328114,27-03-2022,18:25:00,18:40:00,conditions Sunny,Medium,Bad,Drinks,scooter,Single,No,Metropolitian
5,0xc4af,GOARES04DEL01,26,26.0,15.569600,73.742294,15.579600,73.752294,15-02-2022,09:45:00,09:55:00,conditions Fog,Low,Good,Drinks,motorcycle,Single,No,Metropolitian

In [28]:
df["Weatherconditions"].unique()

array(['conditions Windy', 'conditions Stormy', 'conditions Fog',
       'conditions Sunny', 'conditions Cloudy', 'conditions Sandstorms'],
      dtype=object)

In [29]:
df['Weatherconditions'] = df['Weatherconditions'].str.split().str[-1]

In [30]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
1,0x3474,BANGRES15DEL01,28,28.0,12.975377,77.696664,13.085377,77.806664,29-03-2022,20:30:00,20:35:00,Windy,Jam,Good,Snack,motorcycle,Single,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,23.0,26.911378,75.789034,27.001378,75.879034,10-03-2022,19:35:00,19:45:00,Stormy,Jam,Good,Drinks,motorcycle,Single,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,21.0,26.766536,75.837333,26.856536,75.927333,02-04-2022,17:15:00,17:20:00,Fog,Medium,Average,Meal,scooter,Single,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,31.0,12.986047,80.218114,13.096047,80.328114,27-03-2022,18:25:00,18:40:00,Sunny,Medium,Bad,Drinks,scooter,Single,No,Metropolitian
5,0xc4af,GOARES04DEL01,26,26.0,15.569600,73.742294,15.579600,73.752294,15-02-2022,09:45:00,09:55:00,Fog,Low,Good,Drinks,motorcycle,Single,No,Metropolitian

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10291 entries, 1 to 11398
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           10291 non-null  object
 1   Delivery_person_ID           10291 non-null  object
 2   Delivery_person_Age          10291 non-null  int64
 3   Delivery_person_Ratings      10291 non-null  float64
 4   Restaurant_latitude          10291 non-null  float64
 5   Restaurant_longitude         10291 non-null  float64
 6   Delivery_location_latitude   10291 non-null  float64
 7   Delivery_location_longitude  10291 non-null  float64
 8   Order_Date                   10291 non-null  object
 9   Time_Orderd                  10291 non-null  object
 10  Time_Order_picked            10291 non-null  object
 11  Weatherconditions            10291 non-null  object
 12  Road_traffic_density         10291 non-null  object
 13  Vehicle_condition            10291 non-null  object
 14  Type_of_order                10291 non-null  object
 15  Type_of_vehicle              10291 non-null  object
 16  multiple_deliveries          10291 non-null  object
 17  Festival                     10291 non-null  object
 18  City                         10291 non-null  object
dtypes: float64(5), int64(1), object(13)
memory usage: 1.8+ MB

In [32]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

/tmp/ipykernel_1003/2749299126.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [33]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
1,0x3474,BANGRES15DEL01,28,28.0,12.975377,77.696664,13.085377,77.806664,2022-03-29,20:30:00,20:35:00,Windy,Jam,Good,Snack,motorcycle,Single,No,Metropolitian
2,0x9420,JAPRES09DEL03,23,23.0,26.911378,75.789034,27.001378,75.879034,2022-03-10,19:35:00,19:45:00,Stormy,Jam,Good,Drinks,motorcycle,Single,No,Metropolitian
3,0x72ee,JAPRES07DEL03,21,21.0,26.766536,75.837333,26.856536,75.927333,2022-04-02,17:15:00,17:20:00,Fog,Medium,Average,Meal,scooter,Single,No,Metropolitian
4,0xa759,CHENRES19DEL01,31,31.0,12.986047,80.218114,13.096047,80.328114,2022-03-27,18:25:00,18:40:00,Sunny,Medium,Bad,Drinks,scooter,Single,No,Metropolitian
5,0xc4af,GOARES04DEL01,26,26.0,15.569600,73.742294,15.579600,73.752294,2022-02-15,09:45:00,09:55:00,Fog,Low,Good,Drinks,motorcycle,Single,No,Metropolitian

In [34]:
df["Time_Orderd"] = pd.to_datetime(df["Time_Orderd"])
df["Time_Order_picked"] = pd.to_datetime(df["Time_Order_picked"])
diff = df["Time_Order_picked"] - df["Time_Orderd"]
df["Time_taken_min"] = diff.dt.total_seconds() / 60
df.loc[df["Time_taken_min"] < 0, "Time_taken_min"] += 1440

/tmp/ipykernel_1003/3240256317.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Time_Orderd"] = pd.to_datetime(df["Time_Orderd"])
/tmp/ipykernel_1003/3240256317.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Time_Order_picked"] = pd.to_datetime(df["Time_Order_picked"])

In [35]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken_min
1,0x3474,BANGRES15DEL01,28,28.0,12.975377,77.696664,13.085377,77.806664,2022-03-29,2026-05-26 20:30:00,2026-05-26 20:35:00,Windy,Jam,Good,Snack,motorcycle,Single,No,Metropolitian,5.0
2,0x9420,JAPRES09DEL03,23,23.0,26.911378,75.789034,27.001378,75.879034,2022-03-10,2026-05-26 19:35:00,2026-05-26 19:45:00,Stormy,Jam,Good,Drinks,motorcycle,Single,No,Metropolitian,10.0
3,0x72ee,JAPRES07DEL03,21,21.0,26.766536,75.837333,26.856536,75.927333,2022-04-02,2026-05-26 17:15:00,2026-05-26 17:20:00,Fog,Medium,Average,Meal,scooter,Single,No,Metropolitian,5.0
4,0xa759,CHENRES19DEL01,31,31.0,12.986047,80.218114,13.096047,80.328114,2022-03-27,2026-05-26 18:25:00,2026-05-26 18:40:00,Sunny,Medium,Bad,Drinks,scooter,Single,No,Metropolitian,15.0
5,0xc4af,GOARES04DEL01,26,26.0,15.569600,73.742294,15.579600,73.752294,2022-02-15,2026-05-26 09:45:00,2026-05-26 09:55:00,Fog,Low,Good,Drinks,motorcycle,Single,No,Metropolitian,10.0

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10291 entries, 1 to 11398
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           10291 non-null  object
 1   Delivery_person_ID           10291 non-null  object
 2   Delivery_person_Age          10291 non-null  int64
 3   Delivery_person_Ratings      10291 non-null  float64
 4   Restaurant_latitude          10291 non-null  float64
 5   Restaurant_longitude         10291 non-null  float64
 6   Delivery_location_latitude   10291 non-null  float64
 7   Delivery_location_longitude  10291 non-null  float64
 8   Order_Date                   10291 non-null  datetime64[ns]
 9   Time_Orderd                  10291 non-null  datetime64[ns]
 10  Time_Order_picked            10291 non-null  datetime64[ns]
 11  Weatherconditions            10291 non-null  object
 12  Road_traffic_density         10291 non-null  object
 13  Vehicle_condition            10291 non-null  object
 14  Type_of_order                10291 non-null  object
 15  Type_of_vehicle              10291 non-null  object
 16  multiple_deliveries          10291 non-null  object
 17  Festival                     10291 non-null  object
 18  City                         10291 non-null  object
 19  Time_taken_min               10291 non-null  float64
dtypes: datetime64[ns](3), float64(6), int64(1), object(10)
memory usage: 1.9+ MB

In [37]:
def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    return R * c

df['Distance_km'] = haversine(
    df['Restaurant_latitude'], df['Restaurant_longitude'],
    df['Delivery_location_latitude'], df['Delivery_location_longitude']
)

In [38]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,...,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken_min,Distance_km
1,0x3474,BANGRES15DEL01,28,28.0,12.975377,77.696664,13.085377,77.806664,2022-03-29,2026-05-26 20:30:00,...,Windy,Jam,Good,Snack,motorcycle,Single,No,Metropolitian,5.0,17.076617
2,0x9420,JAPRES09DEL03,23,23.0,26.911378,75.789034,27.001378,75.879034,2022-03-10,2026-05-26 19:35:00,...,Stormy,Jam,Good,Drinks,motorcycle,Single,No,Metropolitian,10.0,13.406029
3,0x72ee,JAPRES07DEL03,21,21.0,26.766536,75.837333,26.856536,75.927333,2022-04-02,2026-05-26 17:15:00,...,Fog,Medium,Average,Meal,scooter,Single,No,Metropolitian,5.0,13.413644
4,0xa759,CHENRES19DEL01,31,31.0,12.986047,80.218114,13.096047,80.328114,2022-03-27,2026-05-26 18:25:00,...,Sunny,Medium,Bad,Drinks,scooter,Single,No,Metropolitian,15.0,17.076259
5,0xc4af,GOARES04DEL01,26,26.0,15.569600,73.742294,15.579600,73.752294,2022-02-15,2026-05-26 09:45:00,...,Fog,Low,Good,Drinks,motorcycle,Single,No,Metropolitian,10.0,1.543933

In [39]:
df.to_csv("Data cleaing.csv")